version: '3.5'

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: pass
      DOCKER_INFLUXDB_INIT_ORG: noOrg
      DOCKER_INFLUXDB_INIT_BUCKET: mainBucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: thisisatoken
    volumes:
      - ./config:/etc/influxdb2
      - ./data:/var/lib/influxdb2