// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: subtube.proto

package subtube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserProfileRpc_CreateUser_FullMethodName      = "/subtube.UserProfileRpc/CreateUser"
	UserProfileRpc_GetUserByHash_FullMethodName   = "/subtube.UserProfileRpc/GetUserByHash"
	UserProfileRpc_UpdateUser_FullMethodName      = "/subtube.UserProfileRpc/UpdateUser"
	UserProfileRpc_DeleteUser_FullMethodName      = "/subtube.UserProfileRpc/DeleteUser"
	UserProfileRpc_CheckUserExists_FullMethodName = "/subtube.UserProfileRpc/CheckUserExists"
)

// UserProfileRpcClient is the client API for UserProfileRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户数据RPC
type UserProfileRpcClient interface {
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// 获取用户数据
	GetUserByHash(ctx context.Context, in *GetUserByHashRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// 更新用户数据
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// 删除用户数据
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// 检查用户是否存在
	CheckUserExists(ctx context.Context, in *GetUserByHashRequest, opts ...grpc.CallOption) (*CheckUserExistsResponse, error)
}

type userProfileRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProfileRpcClient(cc grpc.ClientConnInterface) UserProfileRpcClient {
	return &userProfileRpcClient{cc}
}

func (c *userProfileRpcClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, UserProfileRpc_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileRpcClient) GetUserByHash(ctx context.Context, in *GetUserByHashRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, UserProfileRpc_GetUserByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileRpcClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, UserProfileRpc_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileRpcClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserProfileRpc_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileRpcClient) CheckUserExists(ctx context.Context, in *GetUserByHashRequest, opts ...grpc.CallOption) (*CheckUserExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserExistsResponse)
	err := c.cc.Invoke(ctx, UserProfileRpc_CheckUserExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileRpcServer is the server API for UserProfileRpc service.
// All implementations must embed UnimplementedUserProfileRpcServer
// for forward compatibility.
//
// 用户数据RPC
type UserProfileRpcServer interface {
	// 创建用户
	CreateUser(context.Context, *CreateUserRequest) (*UserProfileResponse, error)
	// 获取用户数据
	GetUserByHash(context.Context, *GetUserByHashRequest) (*UserProfileResponse, error)
	// 更新用户数据
	UpdateUser(context.Context, *UpdateUserRequest) (*UserProfileResponse, error)
	// 删除用户数据
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// 检查用户是否存在
	CheckUserExists(context.Context, *GetUserByHashRequest) (*CheckUserExistsResponse, error)
	mustEmbedUnimplementedUserProfileRpcServer()
}

// UnimplementedUserProfileRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserProfileRpcServer struct{}

func (UnimplementedUserProfileRpcServer) CreateUser(context.Context, *CreateUserRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserProfileRpcServer) GetUserByHash(context.Context, *GetUserByHashRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByHash not implemented")
}
func (UnimplementedUserProfileRpcServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserProfileRpcServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserProfileRpcServer) CheckUserExists(context.Context, *GetUserByHashRequest) (*CheckUserExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserExists not implemented")
}
func (UnimplementedUserProfileRpcServer) mustEmbedUnimplementedUserProfileRpcServer() {}
func (UnimplementedUserProfileRpcServer) testEmbeddedByValue()                        {}

// UnsafeUserProfileRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProfileRpcServer will
// result in compilation errors.
type UnsafeUserProfileRpcServer interface {
	mustEmbedUnimplementedUserProfileRpcServer()
}

func RegisterUserProfileRpcServer(s grpc.ServiceRegistrar, srv UserProfileRpcServer) {
	// If the following call panics, it indicates UnimplementedUserProfileRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserProfileRpc_ServiceDesc, srv)
}

func _UserProfileRpc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileRpcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileRpc_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileRpcServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileRpc_GetUserByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileRpcServer).GetUserByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileRpc_GetUserByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileRpcServer).GetUserByHash(ctx, req.(*GetUserByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileRpc_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileRpcServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileRpc_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileRpcServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileRpc_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileRpcServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileRpc_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileRpcServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileRpc_CheckUserExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileRpcServer).CheckUserExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileRpc_CheckUserExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileRpcServer).CheckUserExists(ctx, req.(*GetUserByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProfileRpc_ServiceDesc is the grpc.ServiceDesc for UserProfileRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProfileRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subtube.UserProfileRpc",
	HandlerType: (*UserProfileRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserProfileRpc_CreateUser_Handler,
		},
		{
			MethodName: "GetUserByHash",
			Handler:    _UserProfileRpc_GetUserByHash_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserProfileRpc_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserProfileRpc_DeleteUser_Handler,
		},
		{
			MethodName: "CheckUserExists",
			Handler:    _UserProfileRpc_CheckUserExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subtube.proto",
}

const (
	StreamerRpc_CreateTubeStreamer_FullMethodName = "/subtube.StreamerRpc/CreateTubeStreamer"
	StreamerRpc_ListStreamerVODs_FullMethodName   = "/subtube.StreamerRpc/ListStreamerVODs"
)

// StreamerRpcClient is the client API for StreamerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 主播业务数据RPC
type StreamerRpcClient interface {
	// 创建需要的业务数据
	CreateTubeStreamer(ctx context.Context, in *CreateStreamerRequest, opts ...grpc.CallOption) (*StreamerResponse, error)
	// 查询主播的vod列表
	ListStreamerVODs(ctx context.Context, in *ListStreamerVODsRequest, opts ...grpc.CallOption) (*StreamerListResponse, error)
}

type streamerRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamerRpcClient(cc grpc.ClientConnInterface) StreamerRpcClient {
	return &streamerRpcClient{cc}
}

func (c *streamerRpcClient) CreateTubeStreamer(ctx context.Context, in *CreateStreamerRequest, opts ...grpc.CallOption) (*StreamerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamerResponse)
	err := c.cc.Invoke(ctx, StreamerRpc_CreateTubeStreamer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerRpcClient) ListStreamerVODs(ctx context.Context, in *ListStreamerVODsRequest, opts ...grpc.CallOption) (*StreamerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamerListResponse)
	err := c.cc.Invoke(ctx, StreamerRpc_ListStreamerVODs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamerRpcServer is the server API for StreamerRpc service.
// All implementations must embed UnimplementedStreamerRpcServer
// for forward compatibility.
//
// 主播业务数据RPC
type StreamerRpcServer interface {
	// 创建需要的业务数据
	CreateTubeStreamer(context.Context, *CreateStreamerRequest) (*StreamerResponse, error)
	// 查询主播的vod列表
	ListStreamerVODs(context.Context, *ListStreamerVODsRequest) (*StreamerListResponse, error)
	mustEmbedUnimplementedStreamerRpcServer()
}

// UnimplementedStreamerRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamerRpcServer struct{}

func (UnimplementedStreamerRpcServer) CreateTubeStreamer(context.Context, *CreateStreamerRequest) (*StreamerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTubeStreamer not implemented")
}
func (UnimplementedStreamerRpcServer) ListStreamerVODs(context.Context, *ListStreamerVODsRequest) (*StreamerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreamerVODs not implemented")
}
func (UnimplementedStreamerRpcServer) mustEmbedUnimplementedStreamerRpcServer() {}
func (UnimplementedStreamerRpcServer) testEmbeddedByValue()                     {}

// UnsafeStreamerRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamerRpcServer will
// result in compilation errors.
type UnsafeStreamerRpcServer interface {
	mustEmbedUnimplementedStreamerRpcServer()
}

func RegisterStreamerRpcServer(s grpc.ServiceRegistrar, srv StreamerRpcServer) {
	// If the following call panics, it indicates UnimplementedStreamerRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamerRpc_ServiceDesc, srv)
}

func _StreamerRpc_CreateTubeStreamer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerRpcServer).CreateTubeStreamer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamerRpc_CreateTubeStreamer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerRpcServer).CreateTubeStreamer(ctx, req.(*CreateStreamerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamerRpc_ListStreamerVODs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamerVODsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerRpcServer).ListStreamerVODs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamerRpc_ListStreamerVODs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerRpcServer).ListStreamerVODs(ctx, req.(*ListStreamerVODsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamerRpc_ServiceDesc is the grpc.ServiceDesc for StreamerRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamerRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subtube.StreamerRpc",
	HandlerType: (*StreamerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTubeStreamer",
			Handler:    _StreamerRpc_CreateTubeStreamer_Handler,
		},
		{
			MethodName: "ListStreamerVODs",
			Handler:    _StreamerRpc_ListStreamerVODs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subtube.proto",
}
