// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: subtube.proto

package subtube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash         string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MaxTrackingLimit int32                  `protobuf:"varint,4,opt,name=max_tracking_limit,json=maxTrackingLimit,proto3" json:"max_tracking_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_subtube_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetMaxTrackingLimit() int32 {
	if x != nil {
		return x.MaxTrackingLimit
	}
	return 0
}

type CreateUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserHash         string                 `protobuf:"bytes,1,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	MaxTrackingLimit int32                  `protobuf:"varint,3,opt,name=max_tracking_limit,json=maxTrackingLimit,proto3" json:"max_tracking_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_subtube_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetMaxTrackingLimit() int32 {
	if x != nil {
		return x.MaxTrackingLimit
	}
	return 0
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_subtube_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHash      string                 `protobuf:"bytes,1,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByHashRequest) Reset() {
	*x = GetUserByHashRequest{}
	mi := &file_subtube_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByHashRequest) ProtoMessage() {}

func (x *GetUserByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByHashRequest.ProtoReflect.Descriptor instead.
func (*GetUserByHashRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByHashRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_subtube_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{4}
}

type UpdateUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash         string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MaxTrackingLimit int32                  `protobuf:"varint,4,opt,name=max_tracking_limit,json=maxTrackingLimit,proto3" json:"max_tracking_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_subtube_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetMaxTrackingLimit() int32 {
	if x != nil {
		return x.MaxTrackingLimit
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_subtube_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *UserProfile           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_subtube_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{7}
}

func (x *UserProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserProfileResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

type UserProfileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Users         []*UserProfile         `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileListResponse) Reset() {
	*x = UserProfileListResponse{}
	mi := &file_subtube_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileListResponse) ProtoMessage() {}

func (x *UserProfileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileListResponse.ProtoReflect.Descriptor instead.
func (*UserProfileListResponse) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{8}
}

func (x *UserProfileListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserProfileListResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_subtube_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsResponse) Reset() {
	*x = CheckUserExistsResponse{}
	mi := &file_subtube_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsResponse) ProtoMessage() {}

func (x *CheckUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateStreamerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamerRequest) Reset() {
	*x = CreateStreamerRequest{}
	mi := &file_subtube_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamerRequest) ProtoMessage() {}

func (x *CreateStreamerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamerRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamerRequest) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{11}
}

func (x *CreateStreamerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StreamerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamerResponse) Reset() {
	*x = StreamerResponse{}
	mi := &file_subtube_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamerResponse) ProtoMessage() {}

func (x *StreamerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtube_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamerResponse.ProtoReflect.Descriptor instead.
func (*StreamerResponse) Descriptor() ([]byte, []int) {
	return file_subtube_proto_rawDescGZIP(), []int{12}
}

func (x *StreamerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamerResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StreamerResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StreamerResponse) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_subtube_proto protoreflect.FileDescriptor

const file_subtube_proto_rawDesc = "" +
	"\n" +
	"\rsubtube.proto\x12\asubtube\"~\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12,\n" +
	"\x12max_tracking_limit\x18\x04 \x01(\x05R\x10maxTrackingLimit\"t\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\tuser_hash\x18\x01 \x01(\tR\buserHash\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12,\n" +
	"\x12max_tracking_limit\x18\x03 \x01(\x05R\x10maxTrackingLimit\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"3\n" +
	"\x14GetUserByHashRequest\x12\x1b\n" +
	"\tuser_hash\x18\x01 \x01(\tR\buserHash\"\x14\n" +
	"\x12GetAllUsersRequest\"\x84\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12,\n" +
	"\x12max_tracking_limit\x18\x04 \x01(\x05R\x10maxTrackingLimit\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"s\n" +
	"\x13UserProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.subtube.UserProfileR\x04user\"_\n" +
	"\x17UserProfileListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x05users\x18\x02 \x03(\v2\x14.subtube.UserProfileR\x05users\"H\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x17CheckUserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"+\n" +
	"\x15CreateStreamerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"t\n" +
	"\x10StreamerResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration2\x89\x03\n" +
	"\x0eUserProfileRpc\x12F\n" +
	"\n" +
	"CreateUser\x12\x1a.subtube.CreateUserRequest\x1a\x1c.subtube.UserProfileResponse\x12L\n" +
	"\rGetUserByHash\x12\x1d.subtube.GetUserByHashRequest\x1a\x1c.subtube.UserProfileResponse\x12F\n" +
	"\n" +
	"UpdateUser\x12\x1a.subtube.UpdateUserRequest\x1a\x1c.subtube.UserProfileResponse\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.subtube.DeleteUserRequest\x1a\x1b.subtube.DeleteUserResponse\x12R\n" +
	"\x0fCheckUserExists\x12\x1d.subtube.GetUserByHashRequest\x1a .subtube.CheckUserExistsResponse2^\n" +
	"\vStreamerRpc\x12O\n" +
	"\x12CreateTubeStreamer\x12\x1e.subtube.CreateStreamerRequest\x1a\x19.subtube.StreamerResponseB#Z\t./subtube\xaa\x02\x15subtuber_dataproviderb\x06proto3"

var (
	file_subtube_proto_rawDescOnce sync.Once
	file_subtube_proto_rawDescData []byte
)

func file_subtube_proto_rawDescGZIP() []byte {
	file_subtube_proto_rawDescOnce.Do(func() {
		file_subtube_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subtube_proto_rawDesc), len(file_subtube_proto_rawDesc)))
	})
	return file_subtube_proto_rawDescData
}

var file_subtube_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_subtube_proto_goTypes = []any{
	(*UserProfile)(nil),             // 0: subtube.UserProfile
	(*CreateUserRequest)(nil),       // 1: subtube.CreateUserRequest
	(*GetUserByIdRequest)(nil),      // 2: subtube.GetUserByIdRequest
	(*GetUserByHashRequest)(nil),    // 3: subtube.GetUserByHashRequest
	(*GetAllUsersRequest)(nil),      // 4: subtube.GetAllUsersRequest
	(*UpdateUserRequest)(nil),       // 5: subtube.UpdateUserRequest
	(*DeleteUserRequest)(nil),       // 6: subtube.DeleteUserRequest
	(*UserProfileResponse)(nil),     // 7: subtube.UserProfileResponse
	(*UserProfileListResponse)(nil), // 8: subtube.UserProfileListResponse
	(*DeleteUserResponse)(nil),      // 9: subtube.DeleteUserResponse
	(*CheckUserExistsResponse)(nil), // 10: subtube.CheckUserExistsResponse
	(*CreateStreamerRequest)(nil),   // 11: subtube.CreateStreamerRequest
	(*StreamerResponse)(nil),        // 12: subtube.StreamerResponse
}
var file_subtube_proto_depIdxs = []int32{
	0,  // 0: subtube.UserProfileResponse.user:type_name -> subtube.UserProfile
	0,  // 1: subtube.UserProfileListResponse.users:type_name -> subtube.UserProfile
	1,  // 2: subtube.UserProfileRpc.CreateUser:input_type -> subtube.CreateUserRequest
	3,  // 3: subtube.UserProfileRpc.GetUserByHash:input_type -> subtube.GetUserByHashRequest
	5,  // 4: subtube.UserProfileRpc.UpdateUser:input_type -> subtube.UpdateUserRequest
	6,  // 5: subtube.UserProfileRpc.DeleteUser:input_type -> subtube.DeleteUserRequest
	3,  // 6: subtube.UserProfileRpc.CheckUserExists:input_type -> subtube.GetUserByHashRequest
	11, // 7: subtube.StreamerRpc.CreateTubeStreamer:input_type -> subtube.CreateStreamerRequest
	7,  // 8: subtube.UserProfileRpc.CreateUser:output_type -> subtube.UserProfileResponse
	7,  // 9: subtube.UserProfileRpc.GetUserByHash:output_type -> subtube.UserProfileResponse
	7,  // 10: subtube.UserProfileRpc.UpdateUser:output_type -> subtube.UserProfileResponse
	9,  // 11: subtube.UserProfileRpc.DeleteUser:output_type -> subtube.DeleteUserResponse
	10, // 12: subtube.UserProfileRpc.CheckUserExists:output_type -> subtube.CheckUserExistsResponse
	12, // 13: subtube.StreamerRpc.CreateTubeStreamer:output_type -> subtube.StreamerResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_subtube_proto_init() }
func file_subtube_proto_init() {
	if File_subtube_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subtube_proto_rawDesc), len(file_subtube_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_subtube_proto_goTypes,
		DependencyIndexes: file_subtube_proto_depIdxs,
		MessageInfos:      file_subtube_proto_msgTypes,
	}.Build()
	File_subtube_proto = out.File
	file_subtube_proto_goTypes = nil
	file_subtube_proto_depIdxs = nil
}
